Add note about background-size in backdrop hack
seleb/bitsy-hacks pull request #174
Opened 2021-02-10 04:57 UTC by annie

I was using this hack and noticed that my bg images didn't stretch/shrink to fit the game screen. Adding `background-size: cover` to the CSS seemed to fix it!

2021-02-10 05:22 UTC, seleb requested changes
thanks for the contribution! it looks like you've made this change in the wrong folder though: `dist` is where the automatic build output is placed, so this change would be lost when the next build is triggered. if you move it over to `src` instead it should be good to go

2021-02-12 01:57 UTC, annie commented
ah my b!! fixed ~

2021-02-12 03:27 UTC, seleb approved these changes

2021-02-12 03:29 UTC, merged

2021-02-12 05:20 UTC, seleb commented
:tada: This PR is included in version 15.4.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@bitsy/hecks/v/15.4.2)
- [GitHub release](https://github.com/seleb/bitsy-hacks/releases/tag/v15.4.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: